### ISSUE TITLE
As an analysis designer or implementer I want access to utilities with example code

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/analysis-results-standard#137]
Need sample code in a utilities folder in GitHub

**Comment by ASL-rmarshall** [comment]
I've created a [utilities](https://github.com/cdisc-org/analysis-results-standard/tree/b6c89d1caf1be3bc7afa07b3be1b1ec95e52e3f4/utilities) folder and uploaded to python files into the python subfolder:
- `excel2yaml.py`: converts information from an Excel file (in the format of the accompanying `ARS Template.xlsx` file) into a YAML file.
- `lopa.py`: converts information from a YAML file ReportingEvent to a text file containing a human-readable description of each of the analyses referenced in the ReportingEvent's `listOfPlannedAnalyses`.
Also uploaded the `requirements.txt` file with details of the python packages needed to run these files.
