### ISSUE TITLE
Modeling for Analysis Group

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/analysis-results-standard#14]
A CMAP representation and corresponding LinkML definition for the Analysis Group definition that's needed for each display.

**Comment by ASL-rmarshall** [comment]
The definition of "analysis group" is not very clear.  In some context it seems to be "a way in which data might be grouped for analysis" (e.g. "group by treatment", "group by sex", etc.).  In other situations, it seems to be "a set of data that associated with a particular value of a grouping variable" (e.g. data where TRT1A = "Placebo").  In the example Excel files "AnalysisGroupId" usually seems to refer to the first definition but there are sometimes things like "AnalysisSubGroupId" for the second definition.

I have modelled these as "Analysis Group Set" (the quality by which data is grouped for analysis - e.g., treatment, sex, age group, ethnicity, etc.) and "Analysis Group Member" (a possible value (or combination of values) for the parent grouping quality - e.g. "treatment = Placebo", "treatment = Drug A High Dose", "sex = Male", "sex = Female", etc).

"Analysis group sets" have been implemented as attributes of the reporting event.  Each "analysis group set" has an id, label and set of members.  Each "analysis group member" is modelled as a where clause, with additional:
- **Attributes:** label and order
- **Constraints:** the where clauses referenced in a compound expression must be analysis group member definitions.

### Comments/questions:
- I have added label at the "analysis group set" level.  In the example, this has a value of "Treatment" - i.e. "this is a group by treatment". This may not be necessary and can be removed.
- In the example Excel files, different methods are used to define "total" - either using <grouping variable> IN <list of all other individual value> or using a compound expression.  Are there situations in which one method would be better than the other?

**Comment by bhavinbusa** [comment]
I liked the way you have AnalysisGroupSet and within that you have members and each AnalysisGroupMember has a corresponding Where Clause.  I think we should also consider for multiple levels of Analysis Groups (e.g. Treatment is the top group, followed by Dose, followed by let's say Grade 1, 2, and 3 toxicity grades. This example will have 3 levels). Can the current model cover multiple levels (i.e. more than 2 straddles) of analysis groups?

**Comment by bhavinbusa** [comment]
We can look at couple of examples tomorrow and see how this will work out in the current model where there are more than 2 straddles.

**Comment by bhavinbusa** [comment]
I'm happy with the WhereClause and AnalysisSet part of the model.

**Comment by bhavinbusa** [comment]
I wanted to provide my response to your question...
Question: In the example Excel files, different methods are used to define "total" - either using IN or using a compound expression. Are there situations in which one method would be better than the other?
BB Response: Compound expression will be more suitable when you are combining multiple WhereClauses that uses different variables (e.g. TRTEMFL="Y" and AESER="Y"). But if you want to specify multiple values within a variable, IN operator would be more preferred. Although the user can choose to use multiple WhereClauses even the values are coming from the same dataset/variable. We want this to be flexible and they can choose based on their preference. Does this make sense?

**Comment by ASL-rmarshall** [comment]
> I liked the way you have AnalysisGroupSet and within that you have members and each AnalysisGroupMember has a corresponding Where Clause. I think we should also consider for multiple levels of Analysis Groups (e.g. Treatment is the top group, followed by Dose, followed by let's say Grade 1, 2, and 3 toxicity grades. This example will have 3 levels). Can the current model cover multiple levels (i.e. more than 2 straddles) of analysis groups?

The modelling for AnalysisGroup deals mainly with the definition of the analysis sets/members.  My current thinking is that there may be a difference between _definition_ and _use_ - i.e., (to use your examples), I think there would be three analysis group sets defined (treatment, dose and toxicity grade) - each with a set of members - but I'd expect it to be possible to use these definitions in different ways, either separately or in combination.
