### ISSUE TITLE
Add example usage for element (as needed) in the model

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#147]
This will be to add example usage for element as needed, in the model.

**Comment by ASL-rmarshall** [comment]
I have added simple textual examples for the following:
- `WhereClauseCondition` class
- `groups` slot
- `context` slot
- `sectionType` slot

I have added example YAML content for the following:
- `WhereClause` class
- `WhereClauseCompoundExpression` class
