### ISSUE TITLE
Create URL that points to published documentation files on GitHub using CDISC theme (if applicable)

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#150]
This PBI is to create a URL for external publishing

**Comment by bhavinbusa** [comment]
@cpshadle tagging you here as we may need your help on this PBI

**Comment by cpshadle** [comment]
Happy to help, and I think this is not likely difficult.  Can we discuss this after/at the end of the ARS meeting tomorrow?

**Comment by ASL-rmarshall** [comment]
I configured GitHub Pages for the repository, specifying publishing from the `main` branch and the `/docs` folder, which has published the model documentation at [cdisc-org.github.io/analysis-results-standard](cdisc-org.github.io/analysis-results-standard)
