### ISSUE TITLE
Up-to-date design of grouping (Karl's suggestions)

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/analysis-results-standard#187]
Need to be able to identify the analysis data set for every grouping including data driven groupings.

**Comment by ASL-rmarshall** [comment]
This would potentially involve adding a dataset slot to the GroupingFactor class, which currently only contains the `groupingVariable` slot. Would the slot be called `groupingDataset`, with a description of "For groupings based on a single variable, a reference to the dataset containing the variable upon which grouping is based."?

**Comment by ASL-rmarshall** [comment]
This was discussed on 2024-03-13 and it was agreed that a `groupingDataset` attribute should be added to the `GroupingFactor` class.

**Comment by ASL-rmarshall** [comment]
The model was updated to define a new `groupingDataset` slot and include it in the `GroupingFactor` class.

ARS v1 example files, the ARS Template Excel file and its accompanying `excel2yaml.py` utility program were updated to include/accommodate the `groupingDataset` column/attribute.
