### ISSUE TITLE
Rename the analysisCategorizations slot and the AnalysisCategorization and AnalysisCategory classes

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/analysis-results-standard#205]
Categorizations and their categories can be used for both analyses and outputs, so it would make more sense either to remove "analysis" from the class and slot names:
- `categorizations` slot
- `Categorization` class
- `Category` class

or to add "output":
- `analysisOutputCategorizations` slot
- `AnalysisOutputCategorization` class
-  `AnalysisOutputCategory` class

**Comment by bhavinbusa** [comment]
I personally like more descriptive, 2nd option proposed below.  Thxs

**Comment by ASL-rmarshall** [comment]
I've renamed the slot and two classes to include "Output" (the 2nd option).  The following have been updated:
- model and associated autogenerated content have been updated
- example files
- utility programs
