### ISSUE TITLE
Model for Display framework

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#22]

**Comment by ASL-rmarshall** [comment]
@bhavinbusa I have uploaded updated versions of:

- model/ars_ldm.yaml
- model/ars_ldm.svg
- workfiles/ARS.cmap
- workfiles/examples/example.yaml
- workfiles/examples/example.json

Changes include in this delivery include:
- Moving the definitions of outputs out of the listOfPlannedOutputs into the "outputs" property of the reportingEvent. The outputs defined in the "outputs" property are now referenced by id in the listOfPlannedOutputs
- Adding "displays" as a new property of the reportingEvent. This is where the displays are defined.
- Adding outputDisplays as a property of each output, which contains an ordered list of references to displays defined in the "displays" property.

There are some comments and questions included in the new parts of the cmap.

I did not implement "displayValues" as an alternative to "text" - I think this needs more discussion and would probably be its own PBI.

Please take a look and let me know if you have any comments, questions or concerns.

**Comment by bhavinbusa** [comment]
Hi Richard, here are my comments:
Moving the definitions of outputs out of the listOfPlannedOutputs into the "outputs" property of the reportingEvent. The outputs defined in the "outputs" property are now referenced by id in the listOfPlannedOutputs
**BB Response**: Sounds good - this makes perfect sense. "ListOfPlannedOutputs" can server as a Table of Content which is a very first thing one puts together when starting to develop a shell document. 
Adding "displays" as a new property of the reportingEvent. This is where the displays are defined.
**BB Response**: Looks good, I provided an example of multiple displays within an output and where each display has different treatment arms. I wanted to discuss how such scenario can be accommodated in the current model. Does the display link to AnalysisGroup? We can discuss why you have created a "displays" in same level as the "outputs". Doesn't the display come under an output? 
Adding outputDisplays as a property of each output, which contains an ordered list of references to displays defined in the "displays" property.
**BB Response**: Make sense, per my comment above we may just link the "displays" right here and remove it from the ReportingEvent.

**Comment by bhavinbusa** [comment]
Let's work through an example of the "SubSections" "DisplaySubSection" in our meeting tomorrow. Also how can have an attribute "global" title or for that matter any DisplaySectionType text so it could be used across multiple displays and outputs?

**Comment by bhavinbusa** [comment]
Also let's think through how do we link Displays to "AnalysisGroup" and "AnalysisSet" - as per the example shell I provided one display could have multiple sets of Analysis Group and Analysis Set (possibly?)

**Comment by ASL-rmarshall** [comment]
Moved back to the product backlog because a framework for display should include all of the pieces needed to define a display, which should include the analysis set(s), analysis group(s) and where clause(s).
