### ISSUE TITLE
Definitions for Analysis Set, Analysis Group and Where Clause

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/analysis-results-standard#26]

**Comment by ASL-rmarshall** [comment]
Deliver definitions to Bhavin by 3rd Jan.

**Comment by ASL-rmarshall** [comment]
### Analysis Set
#### Class: AnalysisSet
- **Definition**: A set of subjects whose data are to be included in the main analyses. This should be defined in the statistical section of the protocol. NOTE: There are a number of potential analysis sets, including, for example, the set based upon the intent-to-treat principle. [ICH E9]
- **Comments**: This is the CDISC Glossary definition of "Analysis Set of Subjects", which is available in the NCI Thesaurus ([C142390](https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C142390)).
### Analysis Group
#### Class: AnalysisGroupingFactor
- **Definition**: A factor used to subdivide the subject population for comparative analysis (e.g., treatment, sex, race, age).
- **Comments**: This class was previously named "AnalysisGroupSet".
#### Class: AnalysisGroup
- **Definition**: A subdivision of the subject population based on a defined factor (e.g., subjects whose treatment is Drug A, subjects whose gender is male).
- **Comments**: This class was previously named "AnalysisGroupMember", but was changed because "member" could be misinterpreted as a reference to a subject (i.e., a member of the group). There should be at least two AnalysisGroup classes associated with each AnalysisGroupingFactor class.  
### Where Clause
#### Class: DataSubset
- **Definition**: A subset of data identified by selection criteria for inclusion in the analysis.
- **Comments**: There is a "WhereClause" class defined in the model, which is referenced in the definitions of the AnalysisSet and AnalysisGroup classes. Modelling for the DataSubset class is not yet complete, but it is intended to allow for additional subject- or record-level data restrictions. Note that "Treatment-Emergent Adverse Events" will be as a Data Subset instead of an Analysis Set.

FYI: @bhavinbusa

**Comment by bhavinbusa** [comment]
@ASL-rmarshall definitions looks good. I see you commented "There should be at least two AnalysisGroup classes associated with each AnalysisGroupingFactor class". I think there could be a situation where there is only one AnalysisGroup within a AnalysisGroupFactor. What happens in that case? I recently worked on analysis where it was a single dose/treatment arm was used for analysis. May be we can discuss this tomorrow.

**Comment by ASL-rmarshall** [comment]
@bhavinbusa I have included an additional analysis grouping for "Sex" in the example in the hope that it will help to illustrate the structure, where the instances of the AnalysisGroup class are nested under an instance of the AnalysisGroupingFactor class:
![image](https://user-images.githubusercontent.com/113628824/211012942-c5d81f06-8a52-4773-b969-57d374a93a2d.png)
