### ISSUE TITLE
Modeling for the Results section (Analysis and Result Grouping Vars)

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#38]

**Comment by ASL-rmarshall** [comment]
Modelling for Analysis has been updated to include:
- **`orderedGroupings`**
  - **`order`**: the order in which multiple groupings should be applied during the analysis 
  - **`groupingRef`**: a reference to either:
    - a `SubjectGroupingFactor` defined as one of the `analysisGrouping`s for the `ReportingEvent`.
    - a `DataGroupingFactor` that has been defined in another analysis
  - **`dataGrouping`**: a full specification of a grouping of data records in the analysis dataset.

As part of this change, I also made the following adjustments to the modelling of analysis group(ing)s:
- I converted the `AnalysisGroupingFactor` class to a generic `GroupingFactor` class and created two specializations of it:
  - **`SubjectGroupingFactor`**: something that is used to sub-divide the subject population.  May contain pre-specified `AnalysisGroup`s
  - **`DataGroupingFactor`**: something that is used to sub-divide analysis dataset data records.  May contain pre-specified `DataGroup`s
- Added two attributes to `GroupingFactor`:
  - **`groupingVariable`**: the name of the variable used for grouping (should only be specified if the grouping depends on a single variable - i.e., may not be added for groupings that depend on compound expressions).
  - **`dataDriven`**: a boolean indicator of whether groups are generated from distinct data values in the specified `groupingVariable`.  If "false", prespecified groups should be defined.

I also added a **`dataset`** attribute to the Analysis to specify the single analysis dataset that is used as the input for the analysis.  Note that reference to the full set of subjects for the population is already indicated by the reference to analysisSet, so it is not necessary also to include a reference to the subject-level dataset (e.g., ADSL).

"Result row label description" (mentioned in Bhavin's comment above) has not been addressed during this update.  The label will be identified/assigned when the analysis/data groups are referenced in a display specification.
