### ISSUE TITLE
Modeling for the Results section (Descriptive and Summary Statistics)

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#39]

**Comment by bhavinbusa** [comment]
We will also have to think through how the Statistics will be displayed for output purpose. For ARD, the display of the Stats may not matter. We would like to reuse the Stats across multiple displays - something we should consider as we build this part of the model.

**Comment by ASL-rmarshall** [comment]
This PBI has not been completed during Sprint 6.

**Comment by ASL-rmarshall** [comment]
The CMAP uploaded for PBIs 51 and 52 also includes draft modeling for analysis methods, which may include multiple operations.  Operations may be performed on the analysis variable defined for the analysis and/or with reference to the results of other analysis operations.  For example:
- For analysis "A", which has analysis set=ITT, grouping 1 = treatment, analysis variable=USUBJID:
  - A "count distinct values" operation would give the number of ITT subjects for each treatment.
- For analysis "B", which has analysis set=ITT, grouping 1=treatment, grouping 2=SOC, grouping 3=PT, analysis variable=USUBJID:
  - A "count distinct values" operation would give the number of ITT subjects for each treatment/SOC/PT combination.
  - To calculate percentages, a "calculate percent" operation of analysis "B" may be performed with reference to:
    - The result of the "count distinct values" operation for analysis "B" as the numerator, and
    - The result of the "count distinct values" operation for analysis "A" as the denominator

**Comment by bhavinbusa** [comment]
Excellent! Love the examples, thanks for providing them.
