### ISSUE TITLE
High level modeling for Analysis Result Datasets

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/analysis-results-standard#52]
The CMAP should be updated to include initial plans for the modeling of ARDs, including both their structure and ideas for linkages to analysis components.

**Comment by bhavinbusa** [comment]
This is a good high level model for ARD. One thing we should think about is how could one generate an ARD without necessarily have to have ARM? Can it be self contained? What all are required vs. optional? Can we have ARD as its own class?
