### ISSUE TITLE
Allow multi-level grouping factors if needed

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/analysis-results-standard#56]
The model currently only supports single-level groupings, but it is possible to reference multiple single-level groupings for an analysis.  We need to determine whether there is a need for multi-level grouping factors.  If there is a need, the model should be updated to accommodate them.  Multi- vs single-level groupings may have an impact on the ability to "interleave" results in a display - e.g., in a SOC/PT display.

Assumption (to test): any analysis will only generate results for the lowest level/last grouping factor referenced from the analysis.  If you need results at intermediate grouping levels (e.g. at the SOC level in a SOC/PT display), you have to define a separate analysis where SOC is the lowest level grouping.  If this assumption holds true, multi-level groupings will not be needed because results can be interleaved in a display based on grouping factor ids.

**Comment by drewcdisc** [comment]
Close this one as unnecessary.
