### ISSUE TITLE
Example of the Pivot Table in Excel

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#63]
This PBI is to support hands on workshop and can use 'Summary of TEAE by System Organ Class and Preferred Term' or 'Vital Signs' table example. This will hold the results and will be a good example to show to the attendees at the workshop.

**Comment by ASL-rmarshall** [comment]
I updated the "Demog Shell" sheet in the [PHUSE Connect Examples.xlsx](https://github.com/cdisc-org/analysis-results-standard/blob/a74e0c5751cc552bcff5710027db3605603a6554/workfiles/examples/PHUSE%20Connect%20Workshop/PHUSE%20Connect%20Examples.xlsx) file to include all groups/analyses, and to retrieve values form the "operation_resultPattern" column that I added to the AnalysisResults sheet.  This allowed be to update the rawValue and formattedValue columns in the AnalysisResults sheet with values derived form CDISCPilot01, and the formattedValues are now displayed in the new "Demog Table" sheet.

I also formatted both the "Demog Shell" and "Demog Table" sheets to:
- Grey out the looked up ids
- Use Courier New font for all values expected to be included in the display
- Centre-justify the treatment columns containing results.

If you want to demonstrate adding a new grouped analysis, you can perform the following steps (e.g., on the "Demog Shell" sheet):

1. Select rows 36-63 and right-click > Delete to remove the rows.
2. Select rows 30 and 31 and copy
3. Select cell A36 and hit Enter to paste
4. Go to the AnalysisGroupings sheet, select cell B9 and copy.
5. Go back to the Demog Shell sheet, select cell A36 and paste-special > values
6. Select cell C37 (which should now be displaying "America Indian...") and use the fill handle on the cell (small square at the bottom-right if the cell) to fill the formula down to row 54.
7. Select cells E37:H37 and fill these down to row 54.

**Comment by bhavinbusa** [comment]
Hi Richard, thank you for this. In the Demo Shell and Demog Display, is it
possible to display n before the %? The percentages are displayed before
the n for all categorical summary. If it's not too much of a problem, will
you be able to update this?
