### ISSUE TITLE
As a Library user/dev I want a Swagger spec that defines an endpoint for extracting example metadata.

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/analysis-results-standard#81]
The MVP version of the endpoint will only return JSON. Later versions may offer the chance to transform the data into an alternate format (like maybe CSV).

**Comment by drewcdisc** [comment]
### Talk list for setting up a branch and a release
@ASL-rmarshall , I'm creating this task list to help clarify the steps we need to take in GitHub.  I will be glad to do as much of this as I can.  And I'd also like to use this as an opportunity to spread GitHub knowledge around, since CDISC is going all-in with GitHub. I'm not 100% done with these but they are a great start.


These steps are to prepare to clearly communicate the model upon which the Swagger Spec is defined and to provide a place where that work can be kept.

- [ ] Create a Sprint 10 Branch
  - [ ] Go to Code Tab and click on Branch 
- [ ] Move the latest deliverables through Sprint 10 into that branch
- [ ] Create a Pull Request (PR) to describe the work you want accepted from Sprint 10
- [ ] Use the PR to discuss that work with Bhavin (this should be nothing more than a thumbs-up since the work was already approved from Sprint 10).
- [ ] Have Bhavin (or Drew, if you need assistance with GitHub) approve the PR and merge Sprint 10 into the main branch.
- [ ] Create a new Release for Sprint 10 (v0.10.0)
- [ ] In your Swagger Spec docs, refer to Release v0.10.0 as the basis for your Swagger Spec. Also consider including the URL for the Released ZIP file.
- [ ] Create a branch for Sprint 12  or maybe two branches, one for Swagger and another for P-Value work.
- [ ] Create a PR for merging each branch when it is ready.
- [ ] Get Bhavin or Drew to approve the PR and merge it into main.
- [ ] Get Bhavin

**Comment by ASL-rmarshall** [comment]
I've uploaded the first version of the swagger spec into the openapi folder.

@lexjansen @chowsanthony If possible, could you take a quick look and let me know if anything doesn't look right?
