### ISSUE TITLE
As a developer I want to see the AE SOCPT Example to test out the model

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/analysis-results-standard#83]

**Comment by ASL-rmarshall** [comment]
Several corresponding "Sprint 9 Examples" files have been uploaded into /workfiles/examples. 
These contain the Demog and AE SOCPT examples that were originally defined for PHUSE US Connect, but:
- The structure of the Excel file [Sprint 9 Examples.xlsx](https://github.com/cdisc-org/analysis-results-standard/blob/8191a7b4a7ec0d3a5d59b461629a0445abcc529f/workfiles/examples/Sprint%209%20Examples.xlsx) has been updated to reflect the redesigned model (for standalone method definitions).
- The AE SOCPT example has been completed:
  - Records were added to the AnalysisResults sheet, using the new `groupValue` attribute/slot to specify values for data-driven groupings.
  - AE_SOC_PT Shell and AE_SOC_PT Display sheets were added.
The following corresponding example files were generated from the information in the Excel file:
- [Sprint 9 Examples.yaml](https://github.com/cdisc-org/analysis-results-standard/blob/8191a7b4a7ec0d3a5d59b461629a0445abcc529f/workfiles/examples/Sprint%209%20Examples.yaml) 
- [Sprint 9 Examples.json](https://github.com/cdisc-org/analysis-results-standard/blob/8191a7b4a7ec0d3a5d59b461629a0445abcc529f/workfiles/examples/Sprint%209%20Examples.json)
- [Sprint 9 Examples-LOPA.txt](https://github.com/cdisc-org/analysis-results-standard/blob/8191a7b4a7ec0d3a5d59b461629a0445abcc529f/workfiles/examples/Sprint%209%20Examples-LOPA.txt): a textual representation of the list of planned analyses, including details of each referenced analysis.
