### ISSUE TITLE
As a developer I want to have an endpoint that gets a list of available ARS packages

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/analysis-results-standard#99]
**Acceptance Criteria**:
Have an endpoint that returns a list of collections.

**Comment by ASL-rmarshall** [comment]
This endpoint was originally defined with the intention of returning a list of ARS packages available in the library.  However, we haven't yet defined what a "package" would look like in relation to the example data that we have.  The model currently expects a single reporting event per file, so if a package can contain more than one reporting event, this implies that a package would be some sort of grouping of individual reporting event files.  Could a "package" be defined as a folder containing one or more reporting event files?

The current endpoint returns the entire contents of the example reporting event file as a single-valued list, which has two issues:
- The expected response is a list of references, not a list of contents
- The response is currently a reporting event list (a list containing 1 reporting event), not a package list.
